services:
  - type: web
    name: ems-backend
    env: java
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: PORT
        value: 8080
