ALTER TABLE attendance MODIFY COLUMN status VARCHAR(50);
ALTER TABLE leave_requests MODIFY COLUMN start_date VARCHAR(50), MODIFY COLUMN end_date VARCHAR(50), MODIFY COLUMN reason TEXT;

ALTER TABLE departments ADD COLUMN IF NOT EXISTS max_salary DOUBLE;
